project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "João Granja-Correia"
  site-url: https://joao.granja-correia.eu
  repo-url: https://github.com/joaojcorreia/joaojcorreia.github.io
  search: true

  page-footer:
    left: "&copy; Copyright 2024, João Granja-Correia"
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."

  navbar:
    left:
      - href: index.qmd
        text: Home

      - href: projects/projects.qmd
        text: Projects
        
      - href: blog/blog.qmd
        text: Blog

      - href: about.qmd
        text: About
      
    right:
      - icon: mastodon
        href: https://fediscience.org/@joaogranjacorreia
      - icon: github
        href: https://github.com/joaojcorreia
      - icon: linkedin
        href: https://www.linkedin.com/in/joaojcorreia
      - text: "{{< iconify fa6-brands orcid >}}"
        href: https://orcid.org/0009-0003-8982-278X


format:
  html:
    theme: [darkly, styles_dark.scss]
    mainfont: "Atkinson Hyperlegible"





